apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: weather-app
  name: weather-app-svc
  namespace: sre-coding-test
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: weather-app
  type: NodePort
status:
  loadBalancer: {}
