apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{.Values.weather_app.name}}
  name: weather-app-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{.Values.weather_app.name}}
  type: NodePort
status:
  loadBalancer: {}
